- alias: "MVHR Bypass Toggle Publish"
  trigger:
    platform: state
    entity_id: sensor.mvhr_bypass_select_state
  action:
    service: mqtt.publish
    data_template:
      topic: >
        {% if states('sensor.mvhr_bypass_select_state') == 'on' %}
          comfoair/commands/bypass_activate_1h
        {% elif states('sensor.mvhr_bypass_select_state') == 'off' %}
          comfoair/commands/bypass_deactivate_1h
        {% else %}
          comfoair/commands/bypass_deactivate_1h
        {% endif %}
      payload: "on"


- alias: "MVHR Bypass Toggle Update"
  trigger:
    platform: state
    entity_id: sensor.mvhr_bypass_open_factor
  action:
    - choose:
      - conditions:
        - condition: numeric_state
          entity_id: sensor.mvhr_bypass_open_factor
          above: 84
        sequence:
          - service: input_boolean.turn_on
            entity_id: input_boolean.mvhr_bypass_on_off
      - conditions:
        - condition: numeric_state
          entity_id: sensor.mvhr_bypass_open_factor
          below: 85
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.mvhr_bypass_on_off
